"""Domain entity describing a generated processing product."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Product:
    """A product generated by a processing stage (e.g. an L1B radiance product).

    Because the rasters are large and written by streaming windows to disk, a
    :class:`Product` describes the *outputs by reference* (one path per band)
    plus the metadata and provenance needed to interpret and catalogue them. It
    does not hold pixel data.

    Attributes
    ----------
    level:
        Processing level of the product (e.g. ``"L1B"``).
    scene_id:
        Identifier of the source scene this product derives from.
    units:
        Physical units of the band rasters (e.g.
        ``"W / (m2 sr nm)"`` for TOA spectral radiance).
    bands:
        Mapping of band name to the written output raster path.
    metadata:
        Free-form product metadata (acquisition info, processing parameters).
    provenance:
        Processing lineage: source assets, calibration ids, software version.
    """

    level: str
    scene_id: str
    units: str
    bands: dict[str, Path] = field(default_factory=dict)
    metadata: dict = field(default_factory=dict)
    provenance: dict = field(default_factory=dict)

    @property
    def band_names(self) -> list[str]:
        """Names of the bands written for this product."""
        return list(self.bands.keys())
